language: c++
sudo: required
dist: trusty

addons: &addons
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &packages
      - libfaad-dev
      - libfdk-aac-dev
      - libmpg123-dev
      - libsdl2-dev
      - libgtkmm-3.0-dev
      - g++-6

script:
  - |
    mkdir build_faad
    pushd build_faad
    cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..
    make
  - |
    mkdir build_fdkaac
    pushd build_fdkaac
    cmake -DUSE_FDK-AAC=1 -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..
    make
