language: c++
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons: &addons
  apt:
    packages: &packages
      - libfaad-dev
      - libfaad2
      - libmpg123-dev
      - libsdl2-dev
      - libgtkmm-3.0-dev

script:
  - |
    pushd /tmp
    git clone https://github.com/Opendigitalradio/ka9q-fec.git
    cd ka9q-fec
    mkdir build
    cd build
    cmake ..
    make
    sudo make install
    popd
  - |
    mkdir build
    cd build
    cmake ..
    make

