language: c++
sudo: required
dist: xenial

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libfaad-dev libfdk-aac-dev libmpg123-dev libsdl2-dev libgtkmm-3.0-dev

script:
  - |
    pushd /tmp
    git clone https://github.com/Opendigitalradio/ka9q-fec.git
    cd ka9q-fec
    mkdir build
    cd build
    cmake ..
    make
    sudo make install
    popd
  - |
    mkdir build_faad2
    cd build_faad2
    cmake ..
    make
  - |
    mkdir build_fdkaac
    cd build_fdkaac
    cmake -DUSE_FDK-AAC=1 ..
    make
